// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpwhNDNi-sAwR2T8FYfHJGQdMNqLHgeGY',
    appId: '1:1004094030952:web:61d88119e94465286ca7dd',
    messagingSenderId: '1004094030952',
    projectId: 'howlkarrot4',
    authDomain: 'howlkarrot4.firebaseapp.com',
    storageBucket: 'howlkarrot4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8XR0BUXqbpMmrAoUBJrE33GQNsWMVmk',
    appId: '1:1004094030952:android:d23aa3c85c2435e36ca7dd',
    messagingSenderId: '1004094030952',
    projectId: 'howlkarrot4',
    storageBucket: 'howlkarrot4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNccBY-JsLZxajj-YYFvHRYtes7lXfV6M',
    appId: '1:1004094030952:ios:9a083cd5cb27e65e6ca7dd',
    messagingSenderId: '1004094030952',
    projectId: 'howlkarrot4',
    storageBucket: 'howlkarrot4.firebasestorage.app',
    iosBundleId: 'com.example.karrotClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNccBY-JsLZxajj-YYFvHRYtes7lXfV6M',
    appId: '1:1004094030952:ios:9a083cd5cb27e65e6ca7dd',
    messagingSenderId: '1004094030952',
    projectId: 'howlkarrot4',
    storageBucket: 'howlkarrot4.firebasestorage.app',
    iosBundleId: 'com.example.karrotClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpwhNDNi-sAwR2T8FYfHJGQdMNqLHgeGY',
    appId: '1:1004094030952:web:ece6c1f1a2fe4cb46ca7dd',
    messagingSenderId: '1004094030952',
    projectId: 'howlkarrot4',
    authDomain: 'howlkarrot4.firebaseapp.com',
    storageBucket: 'howlkarrot4.firebasestorage.app',
  );
}
